[bootstrap.packages]
"brew-cask:1password-cli" = "latest"
"brew-cask:font-codicon" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-hack-nerd-font" = "latest"
"brew-cask:font-inconsolata-nerd-font" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:hiddenbar" = "latest"
"brew-cask:karabiner-elements" = "latest"
"brew-cask:meetingbar" = "latest"
"brew:antidote" = "latest"
"brew:ast-grep" = "latest"
"brew:bat" = "latest"
"brew:bottom" = "latest"
"brew:btop" = "latest"
"brew:cheat" = "latest"
"brew:cjson" = "latest"
"brew:cmake" = "latest"
"brew:coreutils" = "latest"
"brew:cosign" = "latest"
"brew:cpanminus" = "latest"
"brew:curl" = "latest"
"brew:docker" = "latest"
"brew:docker-buildx" = "latest"
"brew:docker-compose" = "latest"
"brew:docker-credential-helper" = "latest"
"brew:docker-credential-helper-ecr" = "latest"
"brew:duf" = "latest"
"brew:eza" = "latest"
"brew:fd" = "latest"
"brew:ffmpegthumbnailer" = "latest"
"brew:fzf" = "latest"
"brew:gdal" = "latest"
"brew:gdb" = "latest"
"brew:gh" = "latest"
"brew:ghostscript" = "latest"
"brew:git" = "latest"
"brew:gitleaks" = "latest"
"brew:glab" = "latest"
"brew:gnu-sed" = "latest"
"brew:go-task" = "latest"
"brew:googleworkspace-cli" = "latest"
"brew:gradle" = "latest"
"brew:gradle-completion" = "latest"
"brew:graphicsmagick" = "latest"
"brew:htop" = "latest"
"brew:httpie" = "latest"
"brew:imagemagick" = "latest"
"brew:inetutils" = "latest"
"brew:jj" = "latest"
"brew:jq" = "latest"
"brew:k9s" = "latest"
"brew:kotlin" = "latest"
"brew:kubectx" = "latest"
"brew:kubernetes-cli" = "latest"
"brew:lazygit" = "latest"
"brew:lftp" = "latest"
"brew:libfaketime" = "latest"
"brew:libffi" = "latest"
"brew:libmagic" = "latest"
"brew:libmicrohttpd" = "latest"
"brew:libtool" = "latest"
"brew:libwebsockets" = "latest"
"brew:luarocks" = "latest"
"brew:make" = "latest"
"brew:md5sha1sum" = "latest"
"brew:mise" = "latest"
"brew:mole" = "latest"
"brew:nats-server" = "latest"
"brew:ninja" = "latest"
"brew:nmap" = "latest"
"brew:ollama" = "latest"
"brew:openjdk@17" = "latest"
"brew:openssl@3" = "latest"
"brew:pgcli" = "latest"
"brew:pipx" = "latest"
"brew:poppler" = "latest"
"brew:postgresql@17" = "latest"
"brew:pup" = "latest"
"brew:readline" = "latest"
"brew:redis" = "latest"
"brew:ripgrep" = "latest"
"brew:sd" = "latest"
"brew:shellcheck" = "latest"
"brew:shfmt" = "latest"
"brew:snitch" = "latest"
"brew:sox" = "latest"
"brew:sqlite" = "latest"
"brew:starship" = "latest"
"brew:stylua" = "latest"
"brew:taplo" = "latest"
"brew:tectonic" = "latest"
"brew:tilt" = "latest"
"brew:ttyd" = "latest"
"brew:unar" = "latest"
"brew:unbound" = "latest"
"brew:universal-ctags" = "latest"
"brew:vhs" = "latest"
"brew:watch" = "latest"
"brew:watchman" = "latest"
"brew:weasyprint" = "latest"
"brew:wget" = "latest"
"brew:xmlsectool" = "latest"
"brew:xz" = "latest"
"brew:yq" = "latest"
"brew:zlib" = "latest"
"brew:zsh" = "latest"
