env_path = ["~/.local/bin", "~/bin"]

[env]
EDITOR = 'nvim'
GIT_SSH = 'ssh'
PERL_LOCAL_LIB_ROOT = '~/.local/perl'
PIP_REQUIRE_VIRTUALENV = 'true'
PYTHONBREAKPOINT = 'ipdb.set_trace'
PYTHON_CFLAGS = '-march=native -mtune=native'
PYTHON_CONFIGURE_OPTS = '--enable-shared --enable-optimizations --with-lto --enable-loadable-sqlite-extensions'
RIPGREP_CONFIG_PATH = '/home/bellini/.dotfiles/rg/ripgreprc'

[tools]
# tools
actionlint = 'latest'
argocd = 'latest'
bat = 'latest'
doctl = 'latest'
duf = 'latest'
exa = 'latest'
fd = 'latest'
fzf = 'latest'
github-cli = 'latest'
helm = 'latest'
kube-score = 'latest'
kubectl = 'latest'
kubectx = 'latest'
kustomize = 'latest'
lazygit = 'latest'
lua-language-server = 'latest'
minikube = 'latest'
mykubeseal = 'latest'
pre-commit = 'latest'
ripgrep = 'latest'
rust = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
stylua = 'latest'
yarn = 'latest'
# langs
deno = 'latest'
golang = 'latest'
node = 'latest'
python = ['3.8', '3.9', '3.10', '3.11', '3.12.0rc2']

[plugins]
mykubeseal = 'https://github.com/bellini666/asdf-kubeseal.git'

[settings]
experimental = true
