[tui]
status_line = [
    "model-with-reasoning",
    "current-dir",
    "model",
    "project-name",
    "git-branch",
    "pull-request-number",
    "run-state",
    "permissions",
    "approval-mode",
    "context-used",
    "five-hour-limit",
    "weekly-limit",
    "codex-version",
    "task-progress",
]
status_line_use_colors = true

[tui.model_availability_nux]
gpt-6-astra = 1

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp/oauth"

[mcp_servers.beeper]
url = "http://localhost:23373/v0/mcp"
enabled = false

[mcp_servers.chrome-devtools]
command = "npx"
args = [
    "-y",
    "chrome-devtools-mcp@latest",
    "--headless=true",
    "--isolated=true",
]
enabled = false
