if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-antigen/antigen.zsh

if [ -f "$HOME/.dotfiles/core.sh" ]; then
  source "$HOME/.dotfiles/core.sh"
fi

# oh-my-zsh config
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

antigen use oh-my-zsh

# oh-my-zsh
antigen bundle celery
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle common-aliases
antigen bundle docker
antigen bundle encode64
antigen bundle extract
antigen bundle fzf
antigen bundle gitfast
antigen bundle kubectl
antigen bundle kubectx
antigen bundle lukechilds/zsh-nvm
antigen bundle npm
antigen bundle pip
antigen bundle python
antigen bundle screen
antigen bundle supervisor
antigen bundle systemd
antigen bundle yarn
antigen bundle rust

# github
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle jocelynmallon/zshmarks
antigen bundle wbingli/zsh-wakatime

# theme
antigen theme romkatv/powerlevel10k

antigen apply

unalias rm
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"
alias vi="nvim"
alias vim="nvim"
alias lg="lazygit"
alias luamake=/home/bellini/.local_build/lua-language-server/3rd/luamake/luamake

# workaround until https://github.com/nvm-sh/nvm/issues/3007 is fixed
# nvm() {
#     sh -c '. "$NVM_DIR/nvm.sh" && nvm "$@"' - "$@"
# }

autoload -U compinit && compinit

[[ ! -f ${DOTFILES_DIR}/zsh/p10k.zsh ]] || source ${DOTFILES_DIR}/zsh/p10k.zsh
