# p10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ -f "$HOME/.dotfiles/core.sh" ]; then
  source "$HOME/.dotfiles/core.sh"
fi

if [ -f "${DOTFILES_DIR}/zsh/p10k.zsh"  ]; then
  source "${DOTFILES_DIR}/zsh/p10k.zsh"
fi

if [ -f "$HOME/.config/broot/launcher/bash/br" ]; then
  source "$HOME/.config/broot/launcher/bash/br"
fi

if [ -f "$HOME/.config/op/plugins.sh" ]; then
  source "$HOME/.config/op/plugins.sh"
fi

# oh-my-zsh config
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

# Completion optimization
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompcache"

# History improvements
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY

if [ -f "/opt/homebrew/opt/antidote/share/antidote/antidote.zsh" ]; then
  antidote_dir=/opt/homebrew/opt/antidote/share/antidote
  source ${antidote_dir}/antidote.zsh
elif [ -f "/usr/share/zsh-antidote/antidote.zsh" ]; then
  antidote_dir=/usr/share/zsh-antidote
  source ${antidote_dir}/antidote.zsh
else
  antidote_dir=""
  echo "Antidote not found"
fi

if [[ "${antidote_dir}" != "" ]]; then
  zsh_plugins=${HOME}/.zsh_plugins

  [[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

  fpath=(${antidote_dir}/functions $fpath)
  autoload -Uz antidote

  zstyle ':antidote:bundle' use-friendly-names on

  # Generate a new static file whenever .zsh_plugins.txt is updated.
  if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
    antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
  fi

  source ${zsh_plugins}.zsh
fi

autoload -Uz promptinit && promptinit && prompt powerlevel10k
